name: CI

on:
  push:
    tags:
      - '*'
    branches:
      - main
      - production
  workflow_dispatch:
    secrets:
      GIT_TOKEN:
        required: true
      VERCEL_TOKEN:
        required: true
      VERCEL_ORG_ID:
        required: true
      VERCEL_PROJECT_ID_API:
        required: true
      VERCEL_PROJECT_ID_WEB:
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup PNPM
        id: pnpm-install
        uses: pnpm/action-setup@v2
        with:
          version: 8.15.3
          run_install: false
      - name: Install Dependencies
        run: pnpm install
      - name: Build Project
        run: pnpm build

  deploy-api:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy API to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GIT_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_API }}
          working-directory: apps/api
          vercel-args: ${{ github.ref == 'refs/heads/production' && '--prod' || '' }}

  deploy-web:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Deploy Web to Vercel
        uses: amondnet/vercel-action@v25
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          github-token: ${{ secrets.GIT_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_WEB }}
          working-directory: apps/web
          vercel-args: ${{ github.ref == 'refs/heads/production' && '--prod' || '' }}
